BLACK = 0
BLUE = 1
GREEN = 2
CYAN = 3
RED = 4
MAGENTA = 5
BROWN = 6
LGRAY = 7
DGRAY = 8
LBLUE = 9
LGREEN = 10
LCYAN = 11
LRED = 12
LMAGENTA = 13
YELLOW = 14
WHITE = 15

SCALE = 2
HALF_TILESIZE = 12
TILESIZE = SCALE*HALF_TILESIZE

SCREEN_TILE_WIDTH = 60
SCREEN_TILE_HEIGHT = 32

SCREEN_PIXEL_WIDTH = 12*SCREEN_TILE_WIDTH*SCALE
SCREEN_PIXEL_HEIGHT = 12*SCREEN_TILE_HEIGHT*SCALE

WORLD_HEIGHT = 100
CHUNK_SIZE = 20

TEXT_WIDTH = 8
TEXT_HEIGHT = 12

NO_RENDER = 1

NO_FLAGS = 0
ENVIRONMENTAL = 0
DIRECTIONAL = 1
TRANSPARENT = 2
HALFSCALED = 3
IODIRECTIONAL = 4
ROTATIONAL = 5

ASCII_CODE = 0
COLOR = 1
SCALE_CODE = 2
X_OFFSET = 3
Y_OFFSET = 4
UNSCALED_ROTATION = 2
SCALED_ROTATION = 5

NORTH = 0
SOUTH = 1
EAST = 2
WEST = 3

NORTH_TO_SOUTH = 0
NORTH_TO_EAST = 1
NORTH_TO_WEST = 2
SOUTH_TO_NORTH = 3
SOUTH_TO_EAST = 4
SOUTH_TO_WEST = 5
EAST_TO_NORTH = 6
EAST_TO_SOUTH = 7
EAST_TO_WEST = 8
WEST_TO_NORTH = 9
WEST_TO_SOUTH = 10
WEST_TO_EAST = 11

chars = "!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"
CHAR_CODES = {}
for code, letter in enumerate(chars.strip()):
    CHAR_CODES[letter] = code+33

TICK_SPEED = 1